[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
# solc_version = "0.8.26"
solc_version = "0.8.28"
# 2 different version with uniswap v4
evm_version = "cancun"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

